-- 001_init.sql
CREATE TABLE IF NOT EXISTS _migrations (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL UNIQUE,
  applied_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS products (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  price INT NOT NULL,
  count INT NOT NULL DEFAULT 0,
  img VARCHAR(500) DEFAULT NULL,
  popularity INT NOT NULL DEFAULT 0,
  sale INT NOT NULL DEFAULT 0,
  colors VARCHAR(255) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  firstname VARCHAR(100) NOT NULL,
  lastname VARCHAR(100) NOT NULL,
  username VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  phone VARCHAR(30),
  email VARCHAR(255),
  city VARCHAR(100),
  address VARCHAR(255),
  score INT NOT NULL DEFAULT 0,
  buy INT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS comments (
  id INT AUTO_INCREMENT PRIMARY KEY,
  body TEXT NOT NULL,
  date VARCHAR(50),
  hour VARCHAR(50),
  userID INT,
  productID INT,
  FOREIGN KEY (userID) REFERENCES users(id) ON DELETE SET NULL,
  FOREIGN KEY (productID) REFERENCES products(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS orders (
  id INT AUTO_INCREMENT PRIMARY KEY,
  productID INT,
  userID INT,
  date VARCHAR(50),
  hour VARCHAR(50),
  price INT NOT NULL DEFAULT 0,
  off INT NOT NULL DEFAULT 0,
  sale INT NOT NULL DEFAULT 0,
  popularity INT NOT NULL DEFAULT 0,
  count INT NOT NULL DEFAULT 1,
  sale_count INT NOT NULL DEFAULT 0,
  FOREIGN KEY (productID) REFERENCES products(id) ON DELETE SET NULL,
  FOREIGN KEY (userID) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS offs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(100) NOT NULL UNIQUE,
  percent INT NOT NULL,
  adminID INT DEFAULT NULL,
  productID INT DEFAULT NULL,
  date VARCHAR(50),
  isActive TINYINT NOT NULL DEFAULT 1,
  FOREIGN KEY (productID) REFERENCES products(id) ON DELETE SET NULL
);
